<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://cfcs" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://cfcs" xmlns:intf="http://cfcs" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns1="http://rpc.xml.coldfusion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Macromedia ColdFusion MX version 7,0,2,142559-->
 <wsdl:types>
  <schema targetNamespace="http://rpc.xml.coldfusion" xmlns="http://www.w3.org/2001/XMLSchema">
   <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
   <complexType name="CFCInvocationException">
    <sequence/>
   </complexType>
  </schema>
 </wsdl:types>

   <wsdl:message name="getComicsRequest">

   </wsdl:message>

   <wsdl:message name="getComicsResponse">

      <wsdl:part name="getComicsReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="CFCInvocationException">

      <wsdl:part name="fault" type="tns1:CFCInvocationException"/>

   </wsdl:message>

   <wsdl:portType name="ws">

      <wsdl:operation name="getComics">

         <wsdl:input message="impl:getComicsRequest" name="getComicsRequest"/>

         <wsdl:output message="impl:getComicsResponse" name="getComicsResponse"/>

         <wsdl:fault message="impl:CFCInvocationException" name="CFCInvocationException"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="ws.cfcSoapBinding" type="impl:ws">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getComics">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getComicsRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://cfcs" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="getComicsResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://cfcs" use="encoded"/>

         </wsdl:output>

         <wsdl:fault name="CFCInvocationException">

            <wsdlsoap:fault encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" name="CFCInvocationException" namespace="http://cfcs" use="encoded"/>

         </wsdl:fault>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="HouseofDev">

  <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
http://ws.houseofdev.com/cfcs/ws.cfc?wsdl  </wsdl:documentation>

      <wsdl:port binding="impl:ws.cfcSoapBinding" name="ws.cfc">

         <wsdlsoap:address location="http://ws.houseofdev.com/cfcs/ws.cfc"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
